#!/bin/bash

set -x

set -eo pipefail

# Ensure that any requirements.txt from prior build has been removed.

rm -f requirements.txt

# If a requirements.txt file exists in the /tmp/build directory (added
# via a build secret), use that. This will override any original.

if [ -s /tmp/build/requirements.txt ]; then
    cp /tmp/build/requirements.txt /tmp/src/requirements.txt
fi

# Run the original Python S2I assemble script to install packages.

/usr/libexec/s2i/assemble

# Move files from application source directory to master files directory
# if directory has been specified. This is to facilitate later copying
# of files into a persistent volume on startup of instance.

if [ x"$JUPYTER_MASTER_FILES" != x"" ]; then
    mkdir -p $JUPYTER_MASTER_FILES
    shopt -s dotglob
    mv /opt/app-root/src/* $JUPYTER_MASTER_FILES
fi
