#!/bin/bash

set -eo pipefail

# Generate htdigest password file for webdav access if it doesn't exist.

JUPYTER_ENABLE_WEBDAV=${JUPYTER_ENABLE_WEBDAV:-false}

export JUPYTER_ENABLE_WEBDAV

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    DEPLOYMENT=`echo $HOSTNAME | sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'`
    NAMESPACE=`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`
    WEBDAV_REALM=$NAMESPACE/$DEPLOYMENT
else
    WEBDAV_REALM=jupyter-on-openshift/jupyter-notebooks
fi

WEBDAV_USERFILE=/opt/app-root/etc/webdav.htdigest

export WEBDAV_REALM
export WEBDAV_USERFILE

if [ ! -f $WEBDAV_USERFILE ]; then
    touch $WEBDAV_USERFILE
    if [[ ! -z "${JUPYTER_NOTEBOOK_PASSWORD}" ]]; then
	DIGEST="$( printf "%s:%s:%s" "jupyter" "$WEBDAV_REALM" "$JUPYTER_NOTEBOOK_PASSWORD" | md5sum | awk '{print $1}' )"
	printf "%s:%s:%s\n" "jupyter" "$WEBDAV_REALM" "$DIGEST" >> $WEBDAV_USERFILE
    fi
fi

# Start the Jupyter notebook instance. Run using supervisord if enabled.

if [[ ! -z "${JUPYTER_ENABLE_SUPERVISORD}" ]]; then
    if [ -f /opt/app-root/src/supervisord.conf ]; then
        # Use a supervisord.conf that was provided by the user.

        SUPERVISORD_CONF=/opt/app-root/src/supervisord.conf
    else
        # Generate a supervisord.conf file if one doesn't exist.
        # We create a copy of the original sample so that the
        # original still exists and can be restored if necessary.
        # This is useful when moving everything into a persistent
        # volume and the user is then editing the configuration.

        if [ ! -f /opt/app-root/etc/supervisord.conf ]; then
            cp /opt/app-root/supervisor/supervisord.conf \
               /opt/app-root/etc/supervisord.conf
        fi

        SUPERVISORD_CONF=/opt/app-root/etc/supervisord.conf
    fi

    # Startup supervisord against the configuration and keep it in the
    # foreground so becomes process ID 1 for the container.

    exec /opt/app-root/supervisor/bin/supervisord --nodaemon \
	--configuration $SUPERVISORD_CONF
else
    . /opt/app-root/bin/start-notebook.sh
fi
