#!/bin/bash

set -x

set -eo pipefail

if [ -f /opt/app-root/etc/generate_container_user ]; then
    . /opt/app-root/etc/generate_container_user
fi

# Start the Jupyter notebook instance.

exec jupyter notebook --no-browser --ip=0.0.0.0 --port=8080 "$@"
